### ISSUE TITLE
Facebook Sharer has no activation switch

### ISSUE THREAD

**Issue by kvonspiczak** [panzi/SocialSharePrivacy#50]
Every module has a switch to activate, before the user is able to press the button itself. Why has the Facebook Share Button no switch? I think this button is the only exception, right? Is there anything I've missed?

cheers
Kevin

**Comment by cellardoor77** [comment]
I have the same question. Is there a way to get the facebook share button with the two click activation feature?

**Comment by panzi** [comment]
Because it is only a link and no request to Facebook is made to display it. There is no need for the 2-clicks interaction an it is only included for convenience.

**Comment by lordfpx** [comment]
Will it use open graph if it's only a simple link ?

**Comment by panzi** [comment]
What do you mean? I only know open graph as meta data in `<head>` that a search engine can read. That can't be done in JavaScript anyway.

**Comment by lordfpx** [comment]
Yes, I know they are HTML meta elements.
Does the current facebook link use Open Graph metas like the facebook API (the JS version of the share button)?

**Comment by panzi** [comment]
Oh, you mean if it reads any og meta tags? Sorry, no, it doesn't.
