### ISSUE TITLE
Multilingual site support

### ISSUE THREAD

**Issue by JasonBarnabe** [panzi/SocialSharePrivacy#53]
I have a multilingual site - greasyfork.org. Users can choose what language they browse in. The site is written in Rails, which combines all JavaScripts together into one compressed file in production mode.

I'm wondering how I can use SocialSharePrivacy with my site so that users will see it in their chosen language. I tried including all the JS for all the languages then specifying for example `lang="en"` on the insertion element, but I end up seeing stuff in Russian (presumably because it's last to load as it's last alphabetically). I also tried specifiying `language: "en"` in the `socialSharePrivacy` call, but still Russian.

Is there a way to make this work?

**Comment by panzi** [comment]
You can get it to work by not combining the language files into the single JavaScript, but instead only loading the appropriate language file. Currently there is no other method to do that, sorry.

**Comment by JasonBarnabe** [comment]
So what does the `language` option do then?

**Comment by panzi** [comment]
That tells Facebook & Co. what language to use.

**Comment by JasonBarnabe** [comment]
Thanks, I got it going more or less how I wanted.
