### ISSUE TITLE
Problem loading social buttons

### ISSUE THREAD

**Issue by distriker** [panzi/SocialSharePrivacy#64]
Hi @panzi,
I am very interested on use your social share privacy system, but I am having problems to apply this to my Wordpress theme. I think that I am doing everything correctly, but there is something that it doesn't work.

In my functions file I have loaded every javascript file needed:
- jquery.socialshareprivacy.min.js
- jquery.socialshareprivacy.min.es.js
- jquery.js (v. 1.11.3)
- scripts.js
In the last file, **scripts.js**, I have the following piece of code:
```javascript
$(document).ready(function () {
    $('.share').socialSharePrivacy();
});
```
Finally, where I want to load the buttons I have that:
```html
<div class="share"></div>
```
I think that I have follow your instructions correctly, but I don't know what it's happening. I build the code with build.sh (Facebook, Twitter, G+ and Linkedin, with spanish language).
I hope that you, or anyone that know about it, can help me.
Thanks in advance.
Regards, *Iván*

**Comment by panzi** [comment]
Does it work if change the order of the JavaScript files to this?

   * jquery.js
   * jquery.socialshareprivacy.min.js
   * jquery.socialshareprivacy.min.es.js
   * scripts.js

	-Mathias Panzenböck (panzi)

Am 2015-06-29 um 05:54 schrieb Iván:

**Comment by distriker** [comment]
Yes, it works changing order of the JavaScript files... I didn't think on that. Sorry for that. Thank you @panzi.
Regards, *Iván*

**Comment by panzi** [comment]
No problem. Glad it works now!

Am 2015-06-29 um 13:37 schrieb Iván:
