### ISSUE TITLE
Facebook share should open in a new popup, not new tab

### ISSUE THREAD

**Issue by ssstofff** [panzi/SocialSharePrivacy#68]
Where to update code in order to have Facebook Share opens in a new window popup as for example the twitter share does?

**Comment by panzi** [comment]
One would need to change the `<a target="_blank" ...>` in `javascripts/modules/fbshare.js` to a JavaScript action that uses `window.open(...)`.

**Comment by ssstofff** [comment]
Thx for the hint!

Achieved like this:

`'button'            : function (options, uri, settings) {
     return $('<a/>', {href: '#', onclick: 'window.open("https://www.facebook.com/sharer/sharer.php?'+$.param({u:uri + options.referrer_track}) + '", "FB Share", "height=400,width=600")'}).append(
$('<img >', {alt: options.txt_button,
src: options.path_prefix + (settings.layout === 'line' ? options.line_img : options.box_img)}));
		}`
